mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'story4'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('^', include('story4.urls')),
]

story4/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'story4'
urlpatterns = [
    path('', views.home, name='index'),
    path('experience', views.exp, name='exp'),
    path('education', views.edu, name='edu'),
    path('contact', views.contact, name='contact'),
    path('addFriend', views.addFriend, name='addfriend'),
    path('Flist', views.Flist, name='flist')
]

story4/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=255, default="", blank=False)
    hobby = models.CharField(max_length=255, default="hobby", blank=False)
    year_choices=(('2019', '2019'), ('2018','2018'), ('2017', '2017'), ('2016', '2016'))
    year = models.CharField(choices=year_choices, default='2019', blank=False, null=True, max_length=4)


    def __str__(self):
        return '%s' % self.name

story4/forms.py
from django.forms import ModelForm
from .models import Friend

class FriendForm(ModelForm):
    class Meta:
        model = Friend
        fields = ['name', 'hobby', 'year']

story4/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import FriendForm
from .models import Friend

# Create your views here.
def home(request):
    return render(request, 'index.html')

def exp(request):
    return render(request, 'exp.html')

def edu(request):
    return render(request, 'edu.html')

def contact(request):
    return render(request, 'contact.html')

def Flist(request):
    form1 = Friend.objects.all()
    context = {
        'friend' : form1
    }

    return render(request, 'Friendlist.html', {'Friend':form1})

def addFriend(request):
    if request.method == "POST":
        form = FriendForm(request.POST)
        if form.is_valid():
             friend_item = form.save(commit=False)
             friend_item.save()
             return render(request, 'validform.html')
    else:
        form = FriendForm()
    return render(request, 'Form.html', {'form': form})
             

story4/templates/Form.html
{% load static %}

<!doctype html>
<html>
<head>
    <style>
        form {
	position: absolute;
    top: 26%;
    left: 10%;
    width: 150px;
    height: 100px;
    font-size: 25px;
}
    </style>
<link rel="stylesheet" type="text/css" href="/static/style1.css">	
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">	
<link href="https://fonts.googleapis.com/css?family=Rubik+One" rel="stylesheet">
<meta charset="UTF-8">
<title>Be My Friend</title>
</head>
<body>	
	<div class="ab"></div>
	<div class="ac"></div>
	<div class="cd"></div>
	<h1>Be My Friend!</h1>
    
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_table}}
        <input type="submit" value="Save" onclick="location.href='index.html';">
    </form>
	
	<footer> <p class="q1">"Hardwork never betrays"</p></footer>
	<a href="{% url 'story4:index' %}"><h4>Home Page</h4></a>
</body>
</html>

story4/templates/Friendlist.html
{% load static %}

<!doctype html>
<html>
<head>
    <style>
        div.context {
            font-family: Rubik One;
            position: absolute;
            top: 25%;
            left: 10%;
            right: 10%;
            color: aliceblue;
            text
        }
    </style>
<link rel="stylesheet" type="text/css" href="/static/style1.css">	
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">	
<link href="https://fonts.googleapis.com/css?family=Rubik+One" rel="stylesheet">
<meta charset="UTF-8">
<title>Experience</title>
</head>
<body>	
	<div class="ab"></div>
	<div class="ac"></div>
	<div class="cd"></div>
    <h1>Friend List</h1>
    <div class="context">
        {% for i in Friend %}
            Nama : {{ i.name }} his/her hobby is {{ i.hobby  }} - {{ i.year }} </br>
            
        {% endfor %}


    </div>
	
	
	<footer> <p class="q1">"Hardwork never betrays"</p></footer>
	<a href="{% url 'story4:index' %}"><h4>Home Page</h4></a>
</body>
</html>

story4/templates/contact.html
{% load static %}

<!doctype html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/style3.css">	
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">	
<link href="https://fonts.googleapis.com/css?family=Rubik+One" rel="stylesheet">	
<meta charset="UTF-8">
<title>Contact me</title>
</head>

<body>
	<div class="ab"></div>
	<div class="ac"></div>
	<div class="cd"></div>
	<h1>Contact Me</h1>
	
	<div> 
		<p>Thank you for your time looking at my profile page.
learn more about me through my social media or click 
the button below to be my friend!.</p>
	</div>
	
	<a href="{% url 'story4:addfriend' %}"><button class="bt1">Be My Friend</button></a>
	<a href="https://www.instagram.com/naufalrafiathl/"><button class="bt2">Instagram Profile</button></a>

	<a href="{% url 'story4:index' %}"><h4>Home Page</h4></a>
	<footer> <p class="q1">"Hardwork never betrays"</p></footer>
</body>
</html>

story4/templates/edu.html
{% load static %}

<!doctype html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/style2.css">	
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">	
<link href="https://fonts.googleapis.com/css?family=Rubik+One" rel="stylesheet">	
<meta charset="UTF-8">
<title>Education</title>
</head>

<body>
	<div class="ab"></div>
	<div class="ac"></div>
	<div class="cd"></div>
	<h1>EDUCATION</h1>
	<h2 class="t1">FORMAL</h2>
	<h2 class="t2">INFORMAL</h2>
	
	<ul>
		<li class="first">SD Islam Al-Syukro</li>
		<li class="second">SMPN 17 Tangerang Selatan</li>
		<li class="third">SMAN 6 Tangerang Selatan</li>
	</ul>
	
	<ul>
		<li class="sixth">Dumet School</li>
	</ul>
	
	<a href="{% url 'story4:index' %}"><h4>Home Page</h4></a>
	<footer> <p class="q1">"Hardwork never betrays"</p></footer>
</body>
</html>

story4/templates/exp.html
{% load static %}

<!doctype html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/style1.css">	
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">	
<link href="https://fonts.googleapis.com/css?family=Rubik+One" rel="stylesheet">
<meta charset="UTF-8">
<title>Experience</title>
</head>
<body>	
	<div class="ab"></div>
	<div class="ac"></div>
	<div class="cd"></div>
	<h1>EXPERIENCE</h1>
	
	
	<footer> <p class="q1">"Hardwork never betrays"</p></footer>
	<ul>
		<li class="first">6ixs Cup 2017 ( Event )</li>
		<li class="second">6ixs Cup 2018 ( Creative Team )</li>
		<li class="third">6ixs Cup 2019 ( Creative Team )</li>
		<li class="fourth">Social Project Fakultas Ilmu Komputer 2019</li>
		<li class="fifth">Vice Project Officer Runtime Error 5.0 </li>
	</ul>
	<a href="{% url 'story4:index' %}"><h4>Home Page</h4></a>
</body>
</html>

story4/templates/index.html
{% load static %}

<!doctype html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/style.css">
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">	
<link href="https://fonts.googleapis.com/css?family=Rubik+One" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<meta charset="UTF-8">
<title>Naufal's WDP Story 3</title>
</head>

<body class="mine">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">Naufal's Page</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
		  <ul class="navbar-nav">
			<li class="nav-item active">
			  <a class="nav-link" href="{% url 'story4:index' %}">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'story4:exp' %}">Experience</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'story4:edu' %}">Education</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'story4:contact' %}">Contact</a>
			</li>
		  </ul>
		</div>
	  </nav>
	
<div class="ab"></div>
<div class="ac"></div>
<div class="cd"></div>	
	<img class="prof" src="/static/pp.png">
	<h2 class="skills">SKILLS</h2>
	<div class="rec1">
		<h3 class="name-1"><b>Naufal Rafi Athallah Ramadhan</b></h3>
	<p class="info"> My Name is Naufal, I am 19 years old. I’m a student at Fasilkom Universitas Indonesia. I have learned some of Programming language, including HTML. I also have interest in Web Programming and Web Design </p>
	</div>
<h5 class="html">HTML</h5>
<h5 class="css">CSS</h5>
<h5 class="python">PYTHON</h5>
<h5 class="java">JAVA</h5>

<div class="prog-bar1"><p class="html-prog">40 %</p></div>
<div class="prog-bar2"><p class="csss-prog">35 %</p></div>
<div class="prog-bar3"><p class="python-prog">75 %</p></div>
<div class="prog-bar4"><p class="java-prog">25 %</p></div>
	
<a href="{% url 'story4:exp' %}"><h2 class="exp">EXPERIENCE</h2></a>
<img class="test" src="/static/school-24px 1.png">
<a href="{% url 'story4:edu' %}"><h2 class="edu">EDUCATION</h2></a>
<img class="test1" src="/static/Vector (1).svg">
<a href="{% url 'story4:contact' %}"><h2 class="cont">CONTACT</h2></a>
<img class="test2" src="/static/Vector.svg">



	<footer> <p class="q1">"There is no such thing as talent"</p></footer>
</body>
</html>

story4/templates/validform.html
{% load static %}

<!doctype html>
<html>
<head>
    <style>
        form {
	position: absolute;
    top: 26%;
    left: 10%;
    width: 150px;
    height: 100px;
    font-size: 25px;
}
    button {
        background-color: #e7e7e7; 
        color: black;
        cursor: pointer;
        padding: 20px 40px;
        font-size: 30px;
        position:absolute;
        top:25%;
        left:41%;
    }
    </style>
<link rel="stylesheet" type="text/css" href="/static/style1.css">	
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">	
<link href="https://fonts.googleapis.com/css?family=Rubik+One" rel="stylesheet">
<meta charset="UTF-8">
<title>Thank you</title>
</head>
<body>	
	<div class="ab"></div>
	<div class="ac"></div>
	<div class="cd"></div>
    <h1 class="BRO">Thank you, </h1>
    <div class="but" >
    <a href="{% url 'story4:flist' %}"><button>Friend List</button></a>
    </div>
	<footer> <p class="q1">"Hardwork never betrays"</p></footer>
	<a href="{% url 'story4:index' %}"><h4>Home Page</h4></a>
</body>
</html>